# Generated by Django 2.1.7 on 2019-03-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190223_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_link',
            field=models.CharField(default='/static/images/logo.jpeg', max_length=255),
        ),
    ]
