# Generated by Django 2.1.7 on 2019-03-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_link',
            field=models.CharField(default='images/tide.jpeg', max_length=255),
        ),
    ]
