# Generated by Django 2.1.7 on 2019-03-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190311_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_link',
            field=models.CharField(default='/static/images/tide.jpeg', max_length=255),
        ),
    ]
